### ISSUE TITLE
programatic compilation

### ISSUE THREAD

**Issue by mgood7123** [polymonster/pmfx-shader#10]
is it possible to privide an api that compiles this programatically?

eg

`auto compiledShaderFile = pmfx::compile(pathToShaderFile);`

**Comment by polymonster** [comment]
Hi,

So you want a C++ API for compiling shader at runtime? 

This library is not really designed for that, its aim is to support offline compilation there is an API in my game engine pmtech which loads and uses compiled shaders from pmfx or can compile the source code at runtime:https://github.com/polymonster/pmtech/blob/master/core/put/source/pmfx.h

It's not simple to create a simple encapsulated API which can compile shaders at runtime because it requires so much code for each graphics backend and all the supporting utility code (json parser, threads and so on).

This library was decoupled from pmtech so it could be easily used with other projects, I would like to break out the entire pmfx module from pmtech in future to be more re-usable for other people but with it comes a lot of work.

**Comment by mgood7123** [comment]
> Hi,
> 
> So you want a C++ API for compiling shader at runtime? 
> 
> This library is not really designed for that, its aim is to support offline compilation there is an API in my game engine pmtech which loads and uses compiled shaders from pmfx or can compile the source code at runtime:https://github.com/polymonster/pmtech/blob/master/core/put/source/pmfx.h
> 
> It's not simple to create a simple encapsulated API which can compile shaders at runtime because it requires so much code for each graphics backend and all the supporting utility code (json parser, threads and so on).
> 
> This library was decoupled from pmtech so it could be easily used with other projects, I would like to break out the entire pmfx module from pmtech in future to be more re-usable for other people but with it comes a lot of work.

I understand, thanks

**Comment by mgood7123** [comment]
> Hi,
> 
> So you want a C++ API for compiling shader at runtime?
> 
> This library is not really designed for that, its aim is to support offline compilation there is an API in my game engine pmtech which loads and uses compiled shaders from pmfx or can compile the source code at runtime:https://github.com/polymonster/pmtech/blob/master/core/put/source/pmfx.h
> 
> It's not simple to create a simple encapsulated API which can compile shaders at runtime because it requires so much code for each graphics backend and all the supporting utility code (json parser, threads and so on).
> 
> This library was decoupled from pmtech so it could be easily used with other projects, I would like to break out the entire pmfx module from pmtech in future to be more re-usable for other people but with it comes a lot of work.

pmtech looks amazing
